version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    environment:
      - APP_ID: ndjffnpnjoipcpbpfkgengipennjbblh
  
    steps:
      - checkout

      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get -y install jq
            yarn install
            yarn bower install
  
      - run:
          name: "Run Tests"
          command: yarn test
  
      - run:
          name: "Package Extension"
          command: |
            yarn gulp build
            cd dist
            zip -Dr useful-issues.zip .
            mv -v useful-issues.zip ../
  
      - deploy:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T useful-issues.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
            fi
